name: Release

on:
  push:
    branches: main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: google-github-actions/release-please-action@a37ac6e4f6449ce8b3f7607e4d97d0146028dc0b # v4
        with:
          release-type: node
          package-name: monorepo-nextjs-tailwindcss-template
